# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5daf93d035af4b5a6d54008de0b4d1cc0c1eeb9a880b8c3f0b5c39ae3de424e620c9d63ddefb60f83d16ca34f0cec8c4746dcf5af1e75f22e16822f6cd25b193

test:
  secret_key_base: df11415585ce3399e906aaa6acfda87e4ffb0cde54ef176cc53abe6b1d8c5b35502520022fe3f5a774fb6637c8deca3211ca77d0cbd3e5f1f177fcb94cb94c66

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
